project:
  type: manuscript
  output-dir: docs

notebook-links: global

manuscript:
  article: index.qmd

lang: en-CA

format:
  html:
    comments:
      hypothesis: true
  docx: default
  cerg-typst: default
editor:
  markdown:
    wrap: 80
    canonical: true
execute:
  freeze: true