---
title: Optimizing sampling and monitoring of species interactions within Biodiversity Observation Networks
authors:
  - name: Gabriel Dansereau
    affiliation:
        - ref: udem
        - ref: qcbs
    email: gabriel.dansereau@umontreal.ca
    roles:
        - writing
        - editing
    corresponding: true
  - name: Michael D. Catchen
    affiliation:
        - ref: udem
        - ref: qcbs
    roles:
        - editing
  - name: Ceres Barros
    affiliation:
        - ref: cfs
        - ref: ubc
        - ref: ulaval
    roles:
        - editing
  - name: Timothée Poisot
    affiliation:
        - ref: udem
        - ref: qcbs
    roles:
        - editing
affiliations:
    - id: udem
      name: Université de Montréal
      department: Département de sciences biologiques
      city: Montréal
      region: QC
      country: Canada
    - id: qcbs
      name: Québec Centre for Biodiversity Science
      city: Montréal
      region: QC
      country: Canada
    - id: cfs
      name: Canadian Forest Service
      department: Natural Resources Canada
      city: Victoria
      region: BC
      country: Canada
    - id: ubc
      name: Department of Forest Resources Management
      department: University of British Columbia
      city: Vancouver
      region: BC
      country: Canada
    - id: ulaval
      name: Département des sciences du bois et de la forêt
      department: Université Laval
      city: Québec
      region: QC
      country: Canada 
abstract: Optimal monitoring strategies should be designed to efficiently monitor all essential facets of biodiversity. Yet, species interactions are often overlooked in monitoring designs compared to spatial coverage and species richness, partly due to the inherent difficulty of sampling and monitoring interactions compared to species distributions. Here, we used simulations to test the efficiency of monitoring species interactions within Biodiversity Observations Networks (BONs). We tested several methods for designing and optimizing BONs to monitor species interactions and examined efficiency when increasing the number of monitored sites. We showed that the required sampling effort is considerably higher for interactions, especially when considering that interaction realization and detection realistically depend on species abundance. Thus, expectations to monitor a relevant proportion of interactions within a BON should be lower than expectations to monitor its species. However, from a single-species perspective, optimizing monitoring designs based on a known species range proved an efficient strategy to retrieve its interactions, outperforming designs based on total species or interaction richness. Further efficiency gains required detailed knowledge of where realized interactions occurred, highlighting the need for better knowledge of where interactions are likely to take place and integration of factors influencing interaction realization, such as species abundances. Our results were consistent even when the total species range was over- or underestimated by 10%, which shows a tolerance in the precision of the information required for optimization. Therefore, our results highlight how attainable levels of information can lead to efficiency improvements when designing BONs. With the right target and optimization strategy, and readily available information, such as species ranges, we can therefore guide observation network designs to monitor species interactions as central biodiversity components. <!-- this last sentence sounded bit awkward to me.-->
keywords:
    - biodiversity monitoring
    - species interaction networks
    - biodiversity observation networks
    - sampling design
editor:
  markdown:
    wrap: 80
    canonical: true
citeproc: false
bibliography: references.bib
# csl: https://www.zotero.org/styles/springer-basic-author-date
bibliographystyle: springer-basic-author-date
# keep-typ: true
# citecolor: "#0074d9"
---

```{=typst}
// Define functions for easier citations
#import "@preview/citesugar:0.1.0"
#let citeb(key, supplement: none, style: auto) = {
    show regex("[\(\)\[\]]"): none
    cite(key, supplement: supplement, style: style)
}
```
# Introduction

Biodiversity monitoring should encompass all facets of biodiversity. Article 7
of the Convention on Biological Diversity [@UnitedNations1992ConBio] calls for
Parties to "\[i\]dentify components of biological diversity important for its
conservation and sustainable use", and "\[m\]onitor, through sampling and other
techniques, the components of biological diversity". Biodiversity Observation
Networks (BONs) are promising initiatives to improve monitoring across scales
and biodiversity facets. BONs are coordinated monitoring networks designed to
harmonize observation systems, assist reporting on international assessments,
and reinforce scientific basis in biodiversity monitoring [@Navarro2017MonBio;
@Gonzalez2023GloBio]. BONs can be thematic (Marine BON, Freshwater BON),
national (China BON, French BON, Colombia BON) or regional (Asia-Pacific,
Europe); some represent networks of monitoring sites for systematic monitoring
(China BON) while others represent biodiversity data hubs (French BON)
[@Xu2017OptMon; @Navarro2017MonBio]. Additional BONs are currently in the
development or planification stages, notably in Europe [@Kissling2024ModEff] and
in Canada [@Gonzalez2025BioObs; @Simard2024ResSui], and could eventually be
interlinked into the Global Biodiversity Observation System (GBiOS), a globally
connected network providing capacity to monitor biodiversity change
[@Gonzalez2023GloBio] and guiding actions needed for targets and goals of the
Kunming-Montreal Global Biodiversity framework [@CBD2022DecAdoa].

Recent work highlighted the need for improved sampling designs in BONs and
proper adjustment to monitoring goals. First, current sampling designs over
large scales are often too sparse, at too coarse a scale, too infrequent, and
without temporal replication [@Santana2025LarBio]. For example, recommendations
for more effective spatial sampling designs in Europe included i) stratified
random sampling (with stratification across environmental, anthropogenic and
political gradients or classes, ii) incorporation of existing monitoring sites,
and iii) filling of spatial gaps [@Kissling2024ModEff]. Second, ecological
monitoring design relies on site selection algorithms more often discussed
regarding their capacity to achieve spatial balance and representative samples,
and less frequently for achieving an ecological monitoring goal
[@Norman2025SitSel]. Species richness is the most commonly used biodiversity
measure in monitoring contexts [@Hillebrand2018BioCha], including in discussions
over sampling designs Maximizing richness can efficiently capture functional and
phylogenetic diversity in conservation networks [@Willig2023ProBio]. Yet, the
use of species richness to measure biodiversity change and guide biological
conservation has also been criticized, mainly since trends in species richness
do not properly capture local changes – neglecting species identities and
functional roles – and fail to provide complete information on the persistence
of biodiversity and ecosystem services [@Hillebrand2018BioCha;
@FletcherJr.2025SpeRic; @Aguiar2024UntBio]
<!--two preceding sentences edited for fluidity, check if still consitent with the original meaning-->.
Thus, there is a need to better adjust BON sampling designs to biodiversity
facets beyond species richness.

Species interactions are a central component of biodiversity
[@Valiente-Banuet2015SpeLos; @Harvey2017BriEco; @McCann2007ProBio], critical for
ecosystem functioning and health, yet are undervalued
<!--I would say 'underrepresented' as their value is recognized but hard to bring to practice-->
in biodiversity monitoring and conservation [@Jordano2016ChaEco;
@Dansereau2025OveDis]. Interactions mediate community and ecosystem responses to
change [@Garzke2019TroInt] and can improve our ability to predict responses to
climate change [@Abrego2021AccSpe]. They have their own spatial and
macro-ecological dynamics [@Windsor2023UsiEco; @Mestre2022DisFoo;
@Baiser2019EcoRul; @Dansereau2024SpaExp], and may be lost (or change) faster
than species [@Valiente-Banuet2015SpeLos; @Dore2021RelEff]. Despite a lack of
data at global scales and uneven data availability across different interaction
types and environments [@Hortal2015SevSho; @Poisot2021GloKno], we now have
sufficient conceptual tools to support the added value of species interactions
in designing efficient management actions [@Dansereau2025OveDis;
@Moracho2025RebEco]. Therefore, integrating species interactions into existing
monitoring programs, such as BONs, is something we need to undertake in the near
future.

Prior investigations of interaction sampling did not address how efficiently we
should expect to monitor interactions within the BON framework, nor did studies
on the effectiveness of BONs pay particular attention to the sampling of species
interactions. Instead, much focus has been given on how to assess sampling
completeness and diversity metrics (e.g. `#citeb(<Chacoff2012EvaSam>)`{=typst}
`#citeb(<Chiu2023QuaEst>)`{=typst}) and how sampling effort affects network
properties (e.g. `#citeb(<McLeod2021SamAsy>)`{=typst}). Recent empirical
[@Caron2024TraMod] and theoretical [@Poisot2023GuiPre] results have established
that knowing the network structure (i.e. network properties) does not always
allow knowing <!--for conformity with the use of the continuous form earlier-->
the list of interactions (and vice versa), therefore justifying the need to
sample interactions as their own biological entities. A central challenge to do
so is that the sampling effort required to detect
<!-- documenting (in my brain at least) involves a more descriptive task-->
interactions is much higher than for species (e.g. 500% vs 64% in
`#citeb(<Chacoff2012EvaSam>)`{=typst}). Moreover, evaluating sampling
completeness for interactions is more complex than for species, as it requires
assessing the proportion of forbidden links (i.e. links that cannot occur) due
to life history or morphological restrictions, which in turn requires knowledge
of species natural history and traits [@Jordano2016SamNet]. While some
quantitative network properties such as connectance are less affected by
sampling completeness, network composition and associated
<!--editted for improved flow (admittedly subjective). --> binary measurements
will vary widely if interactions are missed (e.g. number of links,
`#citeb(<Vizentin-Bugoni2016InfSam>)`{=typst}
`#citeb(<Poisot2012DisSpe>)`{=typst}).
<!-- it's not clear to me what you mean by binary measurements. Is it binary (0,1) metrics derived from compositional attributes? In this sense, is no. of links a compositional attribute (it's certainly not a binary measurement/metric). , If so, what's an example of a binary measurement?-->

One way to define expectations for interaction monitoring within BONs is to
consider variation in local sampling from a spatially-explicit
<!--given the context of this work, I prefer 'spatially explicit'; it feels narrower and more defined (i.e. evaluating sampling efficiency across space continuosly -- in every pixel, and what you do here -- rather than using spatial products and coarse resolutions, but not spatially-continuous evaluations)-->
perspective—that is, quantifying sampling effort from specific sites where
interactions are sampled—and use such expectations to improve monitoring
efficiency. Previous evaluations of sampling effort relating to interactions
have used spatial data, but were not tied to biodiversity monitoring efficiency
in spatially-explicit way: they used dataset resampling to measure the variation
of network composition and properties (`#citeb(<Poisot2012DisSpe>)`{=typst}
`#citeb(<Henriksen2019EffNet>)`{=typst}), focused on the effect of spatial scale
(showing that many network structure metrics are robust across scales,
`#citeb(<Wood2015EffSpa>)`{=typst}), or assessed the ability to capture regional
properties (showing that sampling larger to smaller lakes better captures
regional metaweb properties `#citeb(<McLeod2021SamAsy>)`{=typst})
<!--this is sort of what I mean with my previous comment. These were presumably explicitly spatial, but not spatially-explicit. It's a narrow difference that I think needs to be made clear. I tried to improve-->.
We now have frameworks and models to describe and investigate the variation and
detection of interaction networks in space and time [@Poisot2015SpeWhy;
@Cirtwill2019QuaFra; @Catchen2023MisLin; the
<!--minor and v. subjective stylistic change--> next step is to consider how to
optimize monitoring for species interactions. Simulations offer opportunities to
explore such optimizations: for example, to anticipate sampling effects on
estimated network properties compared to a known reference
[@deAguiar2019RevBia], to determine optimal sampling frequency for monitoring
[@Daugaard2024DepFor], and to examine how monitoring efficiency and trends
detection are influenced by the number of monitoring sites under a range of
scenarios and monitoring schemes [@Ficetola2018OptMon].

In this manuscript, we address three key questions. First, what expectations
should we have for monitoring species interactions across space within
Biodiversity Observation Networks? Second, what effect do sampling design
strategies have on the efficiency with which we can detect interactions?
Finally, what available information (e.g. from existing monitoring programs)
could be used to optimize the design of future BONs for interactions and how
precise should such information be to expect efficiency improvements?

We use spatially explicit community simulations to test the efficiency of
monitoring species interactions within BONs, and explore various algorithmic and
design options for network sampling optimization. We aim to define realistic
expectations for monitoring species interactions, in comparison to more commonly
evaluated elements such as species richness and species ranges. We examine how
to assess and compare monitoring efficiency using simulations. We conclude with
recommendations on how this should influence the design of BONs to improve the
monitoring of species interactions as an important biodiversity component.

# Methods

We used simulations to generate species interaction networks, species ranges,
and Biodiversity Observation Networks <!--it's capilatized above and below-->
(BONs) with the goal of evaluating monitoring potential for interaction networks
within BONs. We first detail the steps for the general model we used
([@fig-concept]). We then go over the simulations we performed to investigate
the monitoring of species interactions within BONs, aiming to 1) establish
baseline expectations for the monitoring of interactions; 2) assess
opportunities to improve the monitoring efficiency using different site
selection algorithms and optimization targets; and 3) evaluate how precisely we
need to know a species range to use it as a target for monitoring design.

<!--Fig. 1 - I suggest spelling out the meaning of a in the figure/caption (both p's and n's meanings are in the figure, but a's is less clear) -->

![Conceptual diagram of the workflow and simulations. We used the
spatio-temporal model by @Catchen2023MisLin to generate landscapes with spatial
variation in species and interaction composition. We then designed biodiversity
observation networks (BONs) across the simulated landscapes using a combination
of site selection algorithms (samplers) and optimization targets. We measured
the efficiency of the BON designs for sampling species interactions using a
comparable measure (the number of sites required to detect 80% of the
interactions, *n(0.80)*) across all
simulations.](figures/conceptual_figure.png){#fig-concept}

## General model

We followed the approach and process-based, spatio-temporal model introduced by
@Catchen2023MisLin (building on `#citeb(<Cirtwill2019QuaFra>)`{=typst}) to
simulate interaction realization and detection while accounting for spatial
variation in species occurrences – implemented in
`SpeciesInteractionSamplers.jl`. This model broadly captures the different
processes involved into turning a *potential* interaction (i.e. a biologically
feasible interaction) into a *realized* one (i.e. an interaction that took place
at a specified location), as outlined in @Morales-Castilla2015InfBio. To this
generative model, we added the design of Biodiversity Observation Networks and
the evaluation of sampling efficiency between and across simulations for species
interactions ([@fig-concept]). As implemented, our simulations most closely
resemble predator-prey interactions in food webs. Yet, the approach is
applicable for other network types (e.g. bipartite networks) provided that a
metaweb of interactions and species presence-absence rasters can be obtained and
that interaction rates can be defined based on species abundances or traits (see
model details in `#citeb(<Catchen2023MisLin>)`{=typst}).

### Step 1: Generating interaction networks with spatial variation

We simulated networks with variation in species and interaction composition
across a simulated landscape ([@fig-concept], Step 1) to replicate an ecological
context in which biodiversity monitoring could take place. Here, our intent is
to represent broad-scale landscapes relevant for biodiversity monitoring where
metawebs have recently been projected in space at national and continental
scales—e.g., the spatial predictions of the Canadian mammal metaweb relevant for
CAN-BON [@Dansereau2024SpaExp; @Gonzalez2025BioObs], or the spatial predictions
of TETRA-EU and trophiCH relevant for the European BON [@Braga2019SpaAna;
@RejiChacko2025SpeLos; @Kissling2024ModEff].

First, we generated species ranges representing the distribution of species
across a virtual landscape using neutral landscape models (NLMs,
`#citeb(<Gardner1987NeuMod>)`{=typst}
`#citeb(<Etherington2015NlmPyt>)`{=typst}). NLMs are used to replicate
spatially-autocorrelated distributions similar to fragmented and patchy habitats
in natural landscapes without *a priori* hypotheses or natural processes
[@With1997AppNeu; @Wang2008NeuLan; @Hesselbarth2024ComMet]. NLMs have been used
to generate realistic landscapes in contexts relating to biodiversity
distribution and preservation, for instance to compare avian diversity between
conservation approaches in coffee-growing landscapes [@Valente2022LanLan] or to
assess the potential of a suggested umbrella species in an ecotone
[@Duchardt2023UsiNeu]. NLMs have also been used with species interactions, for
example to evaluate the effect of landscape structure in cross-species disease
transmission between interacting species [@Forero-Munoz2025SpaLan]. Here, we
generated species ranges following the implementation in
SpeciesInteractionSamplers.jl [@Catchen2023MisLin], which 1) uses the fractal
NLM Diamond-Square algorithm (`#citeb(<Fournier1982ComRen>)`{=typst}, also used
and described by `#citeb(<Forero-Munoz2025SpaLan>)`{=typst}) to generate a
probabilistic spatially-autocorrelated range for a species (default
autocorrelation parameter $h$=0.85); 2) randomly <!--right?--> draws a threshold
based on a Beta distribution (default $\alpha$ = 10, $\beta$ = 10); 3) converts
the probabilistic range into a binary one, considering all sites with values
higher than the threshold as presence and those with lower values as absence,
and 4) repeates the process independently for all species (here 75 species). In
the end, this process generates communities of known composition and species
richness at every site in the simulated landscape.

Next, following the spatio-temporal model presented by @Catchen2023MisLin, we
defined the **feasible interactions** between the species by generating a
metaweb using the niche model [@Williams2000SimRul]. The niche model defines
interactions by assigning species a niche position and feeding range, similarly
to body-size relationships between predator and prey, and generates networks
with structural properties similar to empirical food webs [@Williams2000SimRul;
@Gravel2013InfFoo; @Delmas2019AnaEco]. It is widely used as a generative model,
including in the context of investigating interaction sampling
[@Poisot2012DisSpe; @Wood2015EffSpa]. Here, our feasible interactions should be
thought of as trophic interactions within food webs well-aligned with the niche
model, such as predator-prey interactions. Alternative generative models could
be used at this step to extend the methodology to other systems and interactions
types (e.g. bipartite networks).

Combining the species ranges and the metaweb, we verified where species with
feasible interactions co-occur, to build a list of **possible interactions**
[@Catchen2023MisLin] at every location in our landscape. Next, we defined
**realized interactions** by conditioning possible interactions to species
abundances. Rare and low-abundance species are less likely to interact in a
location because they are less likely to encounter one another when compared to
abundant species, leading to neutrally forbidden links [@Catchen2023MisLin;
@Canard2012EmeStr]. The neutral model introduced by @Catchen2023MisLin first
generates a distribution of species relative abundances from a log-normal
distribution (followed by many empirical communities,
`#citeb(<Preston1948ComRar>)`{=typst}; the variance is controlled by a parameter
$\sigma$). It then defines an interaction rate between species pairs based on
the product of their relative abundances, scaled by a fixed realization energy
parameter ($\epsilon$) determining the total expected number of interactions.
Finally, it draws realized interactions from a Poisson distribution parametrized
on the interaction rate (see `#citeb(<Catchen2023MisLin>)`{=typst} for full
details).

Finally, we defined the set of **detected interactions** by also conditioning
the detection of realized interactions on species abundances. Even if an
interaction is realized in a location, sampling must occur at the moment of
interaction for its detection; this is again less likely for low probability
events, like interactions between rare species
<!--'occurring' felt redundant to me-->. @Catchen2023MisLin first establish a
per-species detection probability conditioned on relative abundance and a fixed
scaling parameter ($\alpha$); they then compute the interaction-level detection
rate as the product of the per-species probability, and finally draw the
detected interactions from a Binomial distribution parametrized on the number of
realized interactions and the interaction detection rates.

The result of the general model is a **landscape configuration** with spatial
variation in species and interaction composition and detection. Species
composition, realized interactions, and detected interactions are based on the
process model and known at all locations, allowing to compare the efficacy and
efficiency of sampling strategies at retrieving interactions within the
landscape configuration.

### Step 2: Designing Biodiversity Observation Networks

We designed **Biodiversity Observation Networks (BONs)** across the simulated
landscape and measured their efficiency at monitoring the generated species
interaction networks. The objective of this step is to select the sites that
will form the monitoring network—a BON being a monitoring network for
biodiversity, and for which we here focus specifically on species
interactions—similar to BON examples with grid designs at national (e.g. China
BON, `#citeb(<Xu2017OptMon>)`{=typst} `#citeb(<Yi2022ChiBio>)`{=typst}) and
subnational scales (Québec and Alberta in Canada,
`#citeb(<Simard2024ResSui>)`{=typst} `#citeb(<Burton2014FraAda>)`{=typst}).
@Norman2025SitSel presented an overview of the design and site selection process
accounting for ecological monitoring goals. The design process uses a site
selection algorithm to designate candidate sites for the monitoring network. Key
features of the site selection algorithms include the ability to balance sites
across space for equal representation (see
`#citeb(<Benedetti2017SpaBal>)`{=typst} `#citeb(<Kermorvant2019SpaBal>)`{=typst}
for reviews), to stratify across regions or populations, to use
<!-- edited to avoid repetition with the 'inclusion' used later in this sentence-->
auxiliary site information (environmental or biological) to weight inclusion
probability, and to produce master sampling networks that include current
monitoring sites or from which to select a subset of sites for a specific
monitoring project [@vanDam-Bates2018UsiBal; @Robertson2024WelSam].

Based on the landscape configurations generated in Step 1, we can use **site
selection algorithms** (generally referred to as *samplers*) to distribute
monitoring sites across the landscape, then measure each design's efficiency at
monitoring species interactions. Some algorithms can optimize the location of
sites given different information such as species ranges, species richness or
presence of realized interactions. For example, we can use the Balanced
Acceptance Sampling algorithm [@Robertson2013BasBal] is suitable when aiming to
balance sites across the landscape, given its computational efficiency and its
ability to weight site inclusion probabilities using a layer of weights. On the
other hand, active learning methods like the Uncertainty Sampling algorithm
[@Lewis1994SeqAlg] can be used to optimize sampling given information on element
uncertainty [@Settles2009ActLea]. Instead of focusing on uncertainty, we can
apply this algorithm to target the sites that provide the highest information
gain for the BON, given a layer of 'information' values to maximize. Examples of
active learning relating to biodiversity monitoring and sampling site selection
include improving species range estimation from a smaller number of actively
selected sites [@Lange2023ActLea] and minimizing field data collection costs
based on distances between samples [@Malek2019OptFie].

### Step 3: Defining a comparable measure for sampling efficiency

As interaction composition is known at all locations in our simulated
landscapes, we can determine the **proportion of realized interactions** (noted
$p$) of the focal species
<!--I don't think the focus on focal species was yet made clear up to this point. Does it matter, here, that you refer to prop. of realized interactions of a focal sp vs across all spp?-->that
can be sampled for every generated BON design (e.g. a BON of 50 sites using a
specific site selection algorithm). This proportion can be seen as a 'snapshot'
view of a given BON design's sampling efficiency for that simulated landscape.
The proportion of sampled interactions should increase with the number of sites
in the BON ($n$), although the exact value of $p$ can fluctuate given randomness
in the site selection algorithm. To
<!--I'm not a fan of the term 'remove'. The randomness is still there, but you deal with it-->
ensure a consistent comparison across independent simulations, given their
stochasticity, we state that the **proportion of sampled interactions for a
given number of sites in the BON**, noted $p(n)$, follows an accumulation curve
described by the equation:

$$p(n)=\frac{n}{a + n}$$ {#eq-eff}

where $a$ is the single parameter describing the shape of the sampling curve.
The lower the value for $a$, the faster we reach a high proportion of sampled
interactions. We can identify the value of $a$ yielding the curve with the best
fit with a simulation's results, as described in [Simulation Study
II](#sec-simulation-study-II).

Next, we derived an interpretable efficiency measure based on @eq-eff. Although
the parameter $a$ can be directly compared across samplers, optimization targets
and independent simulations, its value is not intuitive in a monitoring context.
Instead, we used the **number of sites required to sample X% of the
interactions**
<!--I would leave the reference to 80% to the next block of text, since it's not needed at this stage-->
, which can be tied directly to sampling effort and design. Solving @eq-eff
<!--this equation is looks slightly different in Fig. 1--> for $n$, we obtain:

$$n_p(a) = \frac{p \cdot a}{1 - p}$$ {#eq-n_at_p}

where $n_p(a)$ represents the number of sites required to sample a proportion of
interactions $p$, following an efficiency curve described by the parameter $a$.
Here, we fixed $p=0.80$ (80% of the interactions), a threshold representing a
highly effective monitoring outcome (similarly used by @Chacoff2012EvaSam;
@Costa2016SamCom), for which we obtain $n_{0.80} = 4 \cdot a$ using @eq-n_at_p.
$n_{0.80}$ measures the speed at which interactions are detected, and therefore
the sampling efficiency of a BON design within a given landscape. We then used
$n_{0.80}$ values to compare site selection algorithms and optimization targets
in terms of their efficiency—i.e. which allow reaching a high proportion of
sampled interactions more quickly.

## Simulation studies

We performed three simulation studies to investigate the efficiency of
monitoring species interactions within BONs. Across our simulations, we used
landscapes of 100 x 100 pixels, 75 species, and a connectance of 0.2 to generate
metawebs using the niche model. The connectance and number of species are within
the range of values of well-characterized empirical food webs
[@Williams2000SimRul; @Dunne2002NetStr; @Dunne2004NetStr;
@Smith-Ramesh2017GloSyn] commonly used for reference [@Williams2008SucIts;
@Baiser2010ConDet; @Wood2015EffSpa]. These parameters are also within the range
of previous simulation studies on spatial ecological network dynamics, *e.g.*
@Thompson2017DisGov. Next, we chose to keep internal parameters for the
spatio-temporal model implemented in SpeciesInteractionsSamplers.jl constant to
focus on differences between sampling strategies—ensuring that the variation in
monitoring outcomes would only be due to the BON designs—and refer readers to
@Catchen2023MisLin for the detailed discussion over these parameters' effects.
We used the following internal parameters: landscape autocorrelation of $h$ =
0.85, Beta distribution with $\alpha$ = 10 and $\beta$ = 10 to threshold
landscapes, variance of log-normal distribution for relative abundances $\sigma$
= 1.2, realization energy $\epsilon$ = 50,000, and detection scaling $\alpha$ =
50. We implemented our simulations in *Julia* v1.11.9 [@Bezanson2017JulFre]. All
the code used to implement the simulations and perform the analyses is archived
on Zenodo [@Dansereau2026GabNet]. Full computations were run on compute clusters
provided by Calcul Québec and the Digital Research Alliance of Canada.

### Simulation study I: Establishing baseline expectations for the monitoring of interactions

Our first simulation study aimed to establish baselines for the monitoring of
interactions across space, defining expectations for how we could record a
metaweb of interactions using "an existing" BON. This is, we aimed to represent
the case of testing the interaction sampling efficiency of BONs designed to
cover a wide range of taxa and environmental conditions but not necessarily
species interactions (e.g. Québec, China BONs). For this, we designed and tested
spatially balanced BONs <!-- the text what was here felt redundant--> which is
generally considered an effective way to cover environmental space
[@Kermorvant2019SpaBal]. We used the Balanced Acceptance Sampling algorithm
[@Robertson2013BasBal; @Robertson2017ModBal] to generate candidate BONs with a
number of sites between 1 and 500 at intervals of 10 sites, with 50 replicates
for each number of sites, yielding 2,550 BON designs in total
<!-- what were the weightsused?-->. For every design
<!--I think differences between designs need to be reiterated somewhere here-->,
we used the general model (Step 1) to generate an independent landscape
configuration: a specific metaweb, a set of species ranges, an abundance
distribution for the species, and realized interactions. In every one, we
evaluated the sampling efficiency of the BON design in terms of sampling
interactions from the metaweb and in terms of recording species richness. For
interactions, we evaluated each interaction type separately (possible, realized
and detected), counting the number of distinct interactions sampled in the BON,
then evaluated each with regards to the total interactions in the metaweb
(specific to the landscape configuration, but generated with the same
connectance of 0.2 using the niche model). For species richness, we assumed that
all species present at sites in the BON were sampled, then compared the number
of species sampled in the BON against the total species richness across the
landscape (always 75 species).
<!--I reversed the order of the previous to sentences to match the order in which thy are presented on the sentence that preceeds them-->As
a whole, these simulations compared four sampling targets (species richness,
possible interactions, realized interactions, and detected interactions),
establishing baselines for the monitoring of each.

### Simulation study II: Evaluating strategies to optimize the monitoring of interactions for a focal species {#sec-simulation-study-II}

Interaction network sampling and monitoring may be targeted at a focal species
because of its endangered status (e.g. `#citeb(<Rioux2022TroNic>)`{=typst},
because it is at the centre of conservation or restoration programmes (e.g.
[BearConnect](https://bearconnect.org/)), or even due to human-nature conflicts
(e.g. `#citeb(<Baranowska2025LowCon>)`{=typst}). Hence, we also investigated
interaction sampling efficiency from a focal species perspective, by simulating
a virtual observer that would aim to sample all the interactions of a given
species (here known from the metaweb), but who might have different information
on how to optimize the sampling design. Thus, the idea of this simulation study
<!--I was finding the repetition of "focal" was making the text a bit dense/repetitive-->
is to represent a simplified case with a clear objective (retrieving a species'
interactions) and where we have prior knowledge about the system, either through
empirical data or model predictions, that can be used to optimize sampling.

Optimizing focal sampling relies on two elements: the site selection algorithm
(sampler) used and the information provided for optimization. A species range
represents an attainable level of information an interested observer could have,
for instance based on expert knowledge, atlases, or species distribution models.
Therefore, we investigated the case where an observer knows the species' range
across the landscape (presence or absence) and tries to optimize the BON design
to retrieve its interactions. We tested four strategies for comparison: a
*Balanced Sampling* spreading sites across the entire study area (using Balanced
Acceptance Sampling, hereafter BAS), a balanced sampling only within the range
of the focal species (hereafter called *Balanced Within Range*), a *Weighted
Sampling* favouring sites within the species range (adjusting the inclusion
probability in BAS to higher values inside the species
range)<!-- the previous phrasing sounded convoluted to me. please check meaning is correct-->,
and a *Targeted Sampling* selecting sites with higher 'information' values in
the layer provided (using Uncertainty Sampling)
<!--I suggest swapping the order of Balanced Within Range and Weighted Sampling, as the former has more infomation/is more restrictive than the latter; this way we keep a less -> more information gradient-->.
Within the Targeted Sampling strategy, we tested four information targets for
optimization <!--edited for streamlining-->: i) the exact *focal species range*
(our attainable information knowledge for the observer), ii) a *probabilistic
range* for the focal species (representing a less-informed case, similar to the
output of a species distribution model), iii) *species richness* across the
landscape (to represent a holistic level of information about the system, which
an observer might have based on detailed knowledge about biodiversity in a
region), and iv) the location the focal species' *realized interactions* across
the landscape (to represent a best-case scenario, where an observer would know
exactly where to sample the species' interactions
<!--edited for streamlining-->).

We performed 200 independent simulations with independent landscape
configurations (as described in Simulation study I). In each simulation, we
selected the species with the highest degree (number of interactions) in the
metaweb as the focal species for the simulation (this has been previously shown
as an efficient strategy for sampling and conservation,
`#citeb(<Pires2017FriPar>)`{=typst} `#citeb(<deAguiar2019RevBia>)`{=typst}). We
then generated BONs of 1 to 500 sites (at interval increments of 10 sites) using
the three balanced strategies (Balanced Sampling, Balanced Within Range,
Weighted Sampling) and the Targeted Sampling strategy with four optimization
targets (focal species range, probabilistic range, species richness, realized
interactions) <!--edited for clarity-->, with 50 replicates for every number of
sites. For each BON generated, we extracted the number of *unique*
<!--it think it's worthwile highlighting the word "unique" here, but your call of course-->
realized interactions sampled across all sites for the focal species. We then
performed a grid search across possible values of $a$ (from @eq-eff) to identify
the value yielding the curve with the best fit to the simulation's results. To
do so, we fixed $p$ in @eq-eff to the median proportion of sampled interactions
(calculated across replicates for every number of sites in the BONs) and varied
$n$ between 1 and 500 (by increments of 10). For each value of $n$, we varied
$a$ between the $e^{-5}$ and $e^{15}$ range broken into 10,000 spaced values,
hence obtaining one curve of $p \sim n$ per $a$ value. We then selected the $a$
value yielding the curve that minimized the sum of squared errors with respect
to the simulation results
<!--I was having trouble understanding the steps, so I tried to make the text understandable to someone who's not super mathy like me. Please check for accuracy -->.
We searched for values of $a$ on an exponential scale as it allowed for more
gradual control over the curve shape and adjusted the limits to ensure they went
beyond the fitted values on both the lower and higher side. After selecting the
best-fit value for $a$, we evaluated the sampling efficiency for the simulation
using the $n_{0.80}$ measurement described in Step 3 (number of sites required
to detect 80% of the interactions).

Finally, we defined a confidence interval for our $n_0.80$ efficiency
measurement. As the best-fit for $a$ depends on the median result across
replicates, we used the confidence interval of the median to define a lower and
upper bound for values of $a$. We calculated the order statistics delimiting an
90% equal-tailed interval using the normal approximation to the binomial
distribution [@Gibbons2010NonSta] —e.g., at n=50, the 90% confidence interval
for the median goes from the 19th and to the 31st value—and extracted the
corresponding results from our simulations. We performed separate grid searches
for the parameter $a$ using the lower and upper confidence intervals bounds of
the median, thus delimiting the lower and upper bounds for $a$, and subsequently
bounds for $n_{0.80}$. This approach returns a confidence interval for the
sampling efficiency, which we used to compare site selection algorithms and
optimization targets within a specific landscape configuration, given that the
monitoring context is unique in each one (different metawebs and species
ranges). Doing so, we identified which site selection algorithms or optimization
target were more, less or equally <!--purely stylistic edit--> efficient (with
faster rates to reaching high proportions of sampled interactions indicating
higher efficiency), while also quantifying the magnitude of the difference
<!--or simply "quantifying the difference"--> between strategies in a comparable
way between independent simulations.

### Simulation study III: Assessing the precision required when estimating a species range

Building on the Balanced Within Range strategy from Simulation study II, we
assessed how precisely an observer should know the focal species range to
achieve an efficient monitoring. To do so, we compared the Balanced Within Range
strategy, where the balanced sampling design is only generated across the exact
focal species' range, with alternative scenarios where we over- and
underestimated the species range for the BON design. We tested estimation
offsets from 0 to 50% of the true range size, at 2% increment intervals,
generating balanced designs within the over- or underestimated range. For a
given landscape configuration, we extracted the true range size, calculated the
number of sites to add or remove to reach the offset percentage, then used the
non-thresholded probabilistic range (Step 1) to add the absence sites closest to
the threshold (for overestimation) or remove the presence sites closest to the
threshold (for underestimation). This ensured that the original network
(designed on the true range) was kept and only incremented or reduced depending
on the offset value
<!--I'm assuming this is the reason why you simply didn't randomly re-assign the BON sites across the adjusted range?-->.

We followed the same approach as in Simulation study II to design BONs and
measure efficiency using the same 200 simulations with independent landscape
configurations. We generated BONs of 1 to 500 sites for all the estimation
offset ranges (again with 50 replicates at all number of sites) and measured the
efficiency at detecting interactions. We then compared the $n_{0.80}$ values of
each estimation offset range to the $n_{0.80}$ for the true species range, which
we expected would be the most efficient, and used the confidence intervals to
determine which estimation offsets differed from the true range.

# Results

### Simulation study I: Lower sampling expectations for species interactions than species richness

Our results for the baseline spatially-balanced sampling designs highlight a
marked difference between the proportions of sampled species and interactions
(@fig-nbons). Sampled species saturated very quickly, with all species sampled
within less than 25 sites in a BON across the landscape. Possible interactions,
which only depend on co-occurrence of species with a feasible interaction in the
metaweb, also saturated quickly, reaching over 90% of the interactions in the
metaweb within 25 sites and increasing asymptotically afterwards. In contrast,
realized and detected interactions, which account for the impact of species
abundances on interaction realization and detectability, both remained under 25%
of the all metaweb interactions at 100 sampling sites and under 50% at 500
sites. <!-- the two preceeding sentences are long, so I streamlined.-->While the
proportion of sampled realized and detected interactions would keep increasing
with a higher number of sites ($n_{0.80}$ around 2100 and 7300, respectively),
the speed at which they accumulate is notably lower than for species richness or
possible interactions, highlighting the need for a much higher sampling effort
for interactions within spatially-balanced BONs.

<!--The use of "proportion of XXX interactions" is confusing to me. The proportion of sampled interactions is always relative to the metaweb, that is it's always the proportion of sampled *feasible* interactions; but the way you "count" the interaction in a site depedents on more or fewer "conditions" (co-occurrence + abundance adjustments). Phrasing it as "proportion of sampled realized and detected interactions" becomes confusing to me, as it makes me think that you're calculating the proportion of interactions that actually happen in the landscape and are captured in the BON, which I think is not what you're truly measuring here. Presumably, some interactions in the metaweb may never occur (i.e. if spp ranges do not overlap in a landscape, you have fewer potential interactions than feasible interactions). So I propose always referring to the proporion of sampled feasible interations given the total potential, realized and detected interactions. In the preceeding sentence, for example, I would write "While realized and detected interactions would keep increasing with a higher number of sites (...), the speed at which they accumulate feasible interactions is notably lower than for species richness or possible interactions". I would also fix the figure y axis title to say "proportion of sampled feasible interations"-->

![Proportion of sampled species and interactions for a given number of sampling
sites in a spatially-balanced Biodiversity Observation Network (BON) across the
simulated landscape (Simulation Study I). Proportions were calculated with
respect to the total species richness and the total number of interactions in
the metaweb ('feasible interactions'). Lines indicate the median proportion for
a given number of sites, while the shading delimits the 5th and 95th percentiles
across replicates (50 independent replicates per number of sites; 2,550 in
total).](figures/nbon_bands.png){#fig-nbons}

### Simulation study II: Higher efficiency for Targeted Sampling and Balanced Within Range compared to spatially balanced strategies

To better illustrate the results of Simulation Study II, we first showcase the
results for a representative landscape configuration (metaweb, species ranges,
realized interactions)
<!--this parenthesis is not clear. do you mean "a unique set of metaweb, species ranges and realized interactions"?-->
on @fig-samplers; @fig-layers. The conclusions for this landscape configuration
are consistent across most simulations <!--streamlining-->(200 independent
simulations with different landscape configurations), as we highlight on
@fig-eff-comp.

Our focal sampling experiment (which aimed to maximize the sampling of
interactions of a single focal species) showed the Balanced Within Range and
Targeted Sampling strategies to be most efficient at optimizing BON-design based
on a known species range ([@fig-samplers])
<!--the sentence felt long and a bit redundant wrt the start, so I moved the detail to the parenthesis-->.
Balanced sampling -- i.e. a spatially balanced design unrelated to the focal
species, similar to the baseline in Simulation Study I -- performed the worst
among the algorithms tested. Weighted Sampling maintained a better spatial
balance across the landscape, but was notably worse than Targeted Sampling and
Balanced Within Range at maximizing the efficiency for the focal species.
Targeted Sampling and Balanced Within Range performed similarly.

<!--see my earlier comment regarding changing y axis title in this figure-->

![Efficiency of site selection strategies at sampling realized interactions for
a given focal species within Biodiversity Observation Networks (BONs). This
figure displays a representative example comparing four sampling strategies:
three balanced strategies (across the entire area, across the focal species
range only, and using weights to favour the species range) and a targeted
strategy using the species ranges as a fixed optimization target (the species
range). Solid lines indicate the median proportion for a given number of sites
(50 replicates per number of sites), while the shaded bands delimit the 5th and
95th percentile across replicates. The panels on the right illustrate examples
of BONs with 50 sites (coloured points) generated by each strategy over the same
landscape (species presences in yellow, absence in purple, masked area in
white). This showcased example is representative of the most common results
across independent simulations.](figures/focal_samplers.png){#fig-samplers}

Optimizing on the known species range, our proxy for an attainable level of
information an interested user might have, was more efficient at sampling the
focal species' interactions than optimizing based on the probabilistic species
range or on species richness, effectively sampling more than half of the
species' interactions
<!--perhaps here and everywhere where you are talking about the intercations in the metaweb (for a focal sp or not) you could use "feasible interactions", since this is a defined term in the Methods-->([@fig-layers]).
In contrast, optimization based on the location of realized interactions (our
best-case scenario requiring a higher level information) expectedly performed
better, retrieving most of the species'
<!--feasible? (see previous comment)-->interactions.

![Efficiency of optimization targets at sampling realized interactions for a
given focal species within Biodiversity Observation Networks (BONs). This figure
displays a representative example comparing four optimization targets with a
fixed targeted sampler (Uncertainty Sampling). Solid lines indicate the median
proportion for a given number of sites, while the shaded bands delimit the 5th
and 95th percentile across replicates. The panels on the right illustrate
examples of BONs with 50 sites (coloured points) generated by each strategy over
the target landscape (areas in yellow indicate a higher targetting probability,
e.g. species presence or richness, while areas in purple indicate a lower
probability).
<!--see if my edit makes sense. I personally use the term "probability" within optimization targets, but this may be wrong. Your call!-->](figures/focal_optimized.png){#fig-layers}

Comparing optimization options
<!--"by simulation" was unnecessary here. all your methods/results are simulation-based-->
clearly highlighted a consistently more efficient approach across landscape and
metaweb contexts ([@fig-eff-comp]; see also Supp. Mat. for all pair-by-pair
<!--or "pairwise"?--> comparisons), in line
with<!--"consistently... consistent": edited to avoid repetition--> with the
single-simulation example ([@fig-samplers; @fig-layers]). Targeted Sampling was
more efficient than Weighted Sampling in 63% of simulations (lower value for
$n_{0.80}$, indicating a faster detection of <!--feasible?--> interactions), and
both were more efficient than Balanced Acceptance in all simulations
([@fig-eff-comp]A). Targeted Sampling and Balanced Within Range were equally
efficient in all cases. Among optimization targets used with Targeted Sampling
([@fig-eff-comp]B), optimizing on the focal species range was more efficient
than on the probabilistic range or on species richness (78% and 90%,
respectively), but always less efficient than optimizing on realized
interactions.

![Within-simulation comparison of efficiency between site selection strategies
and optimization targets for 200 independent simulations. The comparison value
(x-axis) is the difference between the $n_{0.80}$ (number of sites required to
detect 80% of the focal species' interactions; see @eq-n_at_p) for a given
strategy (A) or target (B) and the $n_{0.80}$ of the reference strategy/target
(in parenthesis). Positive values indicate a higher sampling effort than the
reference, while negative values indicate a lower effort and more efficient
sampling (faster detection of interactions). Equal comparisons (in green) have
overlapping confidence intervals, regardless of the difference sign or
magnitude, while Lower and Higher comparisons (in orange and pink, respectively)
show no $n_{0.80}$ overlap between the compared options
<!--I suggest rephrasing the previous sentence to: "Overlapping n80 confidence intervals indicated no significant difference (Equal, green), whereas non-overalapping confidence intervals indicated significant positive (Higher, pink) or negative (Lower, orange) differences"-->.
The right-side summary panels display the percentage of simulations falling into
each comparison category. Panels A and B use the same reference strategy and
target (Targeted Sampling using the focal species range) to simplify the number
of comparisons displayed <!--streamlined-->. All pairwise comparisons are
available in Supp. Mat.](figures/efficiency_comparison.png){#fig-eff-comp}

### Simulation Study III: Tolerance to over- and underestimation of the focal species range

<!--minor edit to subheading for streamlining-->

Our results highlight a tolerance in the precision of the species range
estimation required for the Balanced Within Range strategy
<!--can we streamline this to "Our results reveal some tolerance of the Balanced Within Range strategy to range over- and under estimation "-->.
Overestimating the range size up to 50% led to a linear increase in the value of
$n_{0.80}$ compared to the $n_{0.80}$ value obtained using the
<!--unnecessary to repeat the strategy. you stated it in the opening sentence-->exact
species range ([@fig-estimations]A, right side)
<!--panel labels in the figure are a)/b), not A/B-->. The $n_{0.80}$ was similar
to the true range up to 10% range overestimation (based on overlapping
confidence intervals); from thereon $n_{0.80}$ increased across all simulations,
indicating lower sampling efficiency (notice the abrupt shift in proportions on
[@fig-estimations]B) <!--edits for streamlining-->. In contrast, underestimating
the species range caused smaller departures in the median $n_{0.80}$ up to -50%,
but a larger variance
<!--I found the "wider range of possible outcomes" to be redundant, that's what the variance means. I suggest keeping that interpretation for the discussion-->
across simulations ([@fig-estimations]A, left side). Importantly, while the
$n_{0.80}$ was stable until a -10% offset and from there it progressively
decreased, in the majority of simulations (\> 70%) this change did not lead to
significant departures even when ranges where underestimated by -50%
([@fig-estimations]B) -- i.e., $n_{0.80}$ confidence intervals continued to
overlap. In the remaining simulations (\< 30%), the $n_{0.80}$ was almost always
higher (less efficient) than for the true range <!--more streamlining edits-->.

![Comparison of efficiencies when over- and underestimating the focal species
range for 200 independent simulations. Results are compared to the Balanced
Within Range strategy applied on the exact species range, whose $n_{0.80}$ value
is used as reference (specific to every simulation). In panel A, we use the
over- and underestimation $n_{0.80}$ in proportion to the reference $n_{0.80}$
(y-axis) given the range estimation offset (x-axis) to highlight the linear
trend and association with the offset percentage for overestimation. The dashed
line at 1.00 indicates exactly equal $n_{0.80}$. Markers are presented at 10%
increments to showcase the variation across simulations. In panel B, we
summarize comparisons across all simulations to display the proportion of each
comparison outcome (equal, higher, lower) at 2% increment intervals. The solid
line represents the actual proportion value, while the shaded bands delimit the
90% confidence intervals for the proportion calculated using the Wilson interval
method [@Brown2001IntEst implemented in
HypothesisTests.jl].](figures/ranges_overlap.png){#fig-estimations}

<!--minor: this figure has panel labels as a) and b), but the previous uses A and B. I would chose one type of labelling for consistency-->

# Discussion

*What should be realistic expectations for sampling and monitoring of species
interactions?*

Our simulations highlight that expectations for monitoring species interactions
within spatially-balanced, general-purpose BONs should be much lower than for
species and community composition. Therefore, interactions will require a (much)
higher monitoring effort across space. Our observations are consistent with
previous ones regarding higher sampling effort required to document
<!--'document' sounds fine to me here, because the detected interactions are merged to 'document' a metaweb-->pollinator
networks [@Chacoff2012EvaSam], yet here framed in the context of BON design and
monitoring across space. Overall, these results reinforce the need for
optimizing sampling designs for species interactions beyond and in complement to
existing monitoring networks, and for recognizing them as a gap to fill in
developing monitoring programs [e.g. European BON, @Kissling2024ModEff].

We can improve interaction coverage with the right optimization method, but
efficiently doing so requires a clear and attainable monitoring objective.
Adopting a single-species perspective (e.g. focusing on interactions for a
keystone or high degree species,
`#citeb(<Pires2017FriPar>)#citeb(<deAguiar2019RevBia>)`{=typst}) can yield
relevant results while relying on attainable levels of information. For example,
the Targeted Sampling and Balanced Within Range strategies can outperform
spatially-balanced designs to monitor interactions for a focal species, while
only relying on a known species range. While these strategies diverge from
spatially-balanced designs, they are similar in intent to targeted design
approaches taken by implemented BONs to improve community monitoring [e.g.,
complementarity-based site selection, @Xu2017OptMon; dynamic off-grid
monitoring, @Burton2014FraAda] and are compatible with BONs focused on
assembling information from several sources in a bottom-up approach [e.g.
CAN-BON, @Gonzalez2025BioObs].

*What strategies and available information are most efficient to optimize
monitoring for species interactions?*

Ecologically-relevant metrics are required to evaluate the performance of
monitoring designs, beyond spatial balance [@Norman2025SitSel]. While many
sampling algorithms can perform similarly for biodiversity monitoring in certain
contexts [@Norman2025SitSel], our results highlighted better options when we can
define a specific target for monitoring, such as a focal species. Optimizing on
a known species range proved an efficient strategy to retrieve its interactions
that was better than optimizing based on more holistic, community-level
information such as species richness (Figures [-@fig-layers; -@fig-eff-comp]) .
This contrasts with earlier accounts where designs based on maximising species
richness also proved efficient to conserve multiple biodiversity facets
[@Willig2023ProBio]. Instead, our results highlight that more information about
an entire system does not always lead to more efficient monitoring, and that
efforts could instead be put towards identifying relevant targets with available
information to guide monitoring design.

Optimizing based on the location of the realized interactions was, as expected,
even more efficient than targeting the species range (Figures [-@fig-layers;
-@fig-eff-comp]). Yet, this represents a best case scenario that is likely
beyond reach in an applied context: it assumes that there is already
pre-existing knowledge on where species interactions can be observed, which is
unlikely to exist for most interactions, species and locations across the globe,
regardless of their relevance for monitoring. Nonetheless, it highlights that
the most important efficiency gains will come from better knowledge of where
interactions are likely to take place. On one hand, better incorporating factors
influencing interaction realization and detection, such as species abundance in
our simulations, will be crucial and potentially more impactful than improving
knowledge or reducing uncertainty over species ranges. Integrating abundances
into network evaluations could be based on species regional abundances
[@RejiChacko2025SpeLos] and would echo similar calls for integration of
abundances and processes into conservation [@FletcherJr.2025SpeRic;
@Dornelas2023LooBac; @Tobias2025BioCon]. On the other hand, our result also
suggest that monitoring will become more efficient over time as we keep
gathering knowledge on interactions, especially if local knowledge of the system
and species under focus is incorporated. Such opportunities should emerge in
recent BON initiatives integrating Indigenous and local community knowledge for
an inclusive view of biodiversity change and recognizing multiple ways of
knowing [e.g. CAN BON, @Gonzalez2025BioObs]. Overall, we should not wait for
perfect knowledge: establishing operational monitoring frameworks to inform
biodiversity conservation and management is possible as we keep gathering new
information, and better ensures we translate knowledge into action
[@Dansereau2025OveDis; @Buxton2021KeyInf].

*How precise should estimations be to expect improvements in monitoring
efficiency?*

A similarly-efficient alternative to targeted sampling is to follow an approach
such as our Balanced Within Range strategy, where we generate a spatially
balanced design across the area believed to be more informative. Our results
from Simulation Study III are encouraging in this sense, as they show we do not
need perfect knowledge when using this strategy (@fig-estimations). The
tolerance we observed to 10% over- and underestimation of the focal species
range size offers an important margin that changes the completeness of
information needed to guide BON design. For instance, our test case of
underestimating a species range highlights that we could focus mainly on the
most certain parts of a predicted species range (e.g. using conformal prediction
<!--the method, not the outputs, right?--> along with species distribution
models, `#citeb(<Poisot2024ConPre>)`{=typst}
<!--replace with https://doi.org/10.1016/bs.aecr.2026.03.001 -->) and expect
similar monitoring efficiency. In certain cases, efficiency could be maintained
even with highly restricted ranges (up to 50% estimation offsets), although such
strategies would warrant further investigation before implementation given the
high variance we observed. On the opposite side, our range overestimation
<!--streamlining-->test case is more analogous to a model
<!--maybe framework or approach?--> focusing on the potential distribution
rather than the realized distribution. While the 10% tolerance zone confirms
some flexibility regarding overestimation, our results highlight that linear
decreases in efficiency should be expected as non-informative sites (regarding
the monitoring objective) are added to the
BON<!--just suggestion to make the text more direct and reliant on previously defined terminology-->.
Yet, as this linear trend is predictable and showed lesser variance, losses in
effieciency can be controlled for during the planning phase to balance
exploration of potential areas of interest and exploitation of more certain ones
(tying in with existing work on adaptive sampling, e.g.
`#citeb(<Andrade-Pacheco2020FinHot>)`{=typst}).

*Results and model applicability*
<!--"Results representativity" felt a bit hard to read-->

We expect our sampling results to be representative for networks well aligned
with the niche model, such as food webs of predator-prey interactions, yet our
simulation approach could be extended to other systems<!--streamlining-->. The
niche model performs well at reproducing structure within the range of
parameters we used here [@Williams2000SimRul; @Williams2008SucIts]; therefore,
we expect our site-selection strategies and optimization test results to hold in
similar systems
<!--streamlining and avoidin repetition with "in such systems" used again below-->.
In contrast, the niche model tends to underestimate the proportion of herbivores
and can perform worse at high species richness, poorly matching extremely rich
and highly resolved food webs [@Williams2008SucIts; @Hale2024HigRes]. Our
conclusions were not tested in such systems, where identifying target species
for focal monitoring may in any case be challenging. In these cases, spatially
balanced monitoring plans may be more effective. Nonetheless
<!--to not use "yet" again-->, our simulation approach is compatible with other
network generators, including variations over the classical niche model or
generators for different network types (e.g. bipartite and plant-pollinator
<!--REF?-->), as well as documented or predicted metawebs. For instance, the
niche model could be parameterized for specific, size-structured empirical
systems [@Gravel2013InfFoo], while herbivory interactions could be included
using documented food webs in place of a simulated metaweb [@Hale2024HigRes].
Future studies could explore multilayer networks with high potential to inform
conservation and management by integrating several interaction types,
information across levels of biological organization, as well as
socio-ecological considerations into monitoring designs [@Madeira2024MulBio;
@deJuan2023UndSoc].

*Recommendations for monitoring*

Detecting species interactions extensively requires higher sampling efforts than
required to detect species presences. While spatially balanced designs are
efficient for more generic biodiversity monitoring purposes, species
interactions may be better sampled using specifically-optimized monitoring
designs
<!--this sounds a little vague to me. How about "species interactions may be better sampled using optimized monitoring designs targetting focal species, or locations where species are known to exist"?-->.
We show the importance of selecting a appropriate target (e.g. a focal species'
interaction) and using attainable information restricting the phenomenon (here
the species range) to optimize monitoring designs efficiently
<!-- I removed the "To do so", because it made it sound like this is THE solution, but I think that depending on the goal, different optimization targets/weights could be used and there may be other considerations we haven't thought of-->.
There is a degree of tolerance in the level of exact information needed (similar
to range over- and
underestimation)<!--this sentence reads awkwardly to me. I suggest "There is a degree of tolerance to the level of information precision needed for optimization" or simply "There is a degree of tolerance to information precision, or lack thereof,"-->,
therefore available information should be used as soon as possible to guide
monitoring<!--this link between tolerance to information error and time sensitivity is not clear to me.-->.

# Acknowledgements

GD was funded by the NSERC Postgraduate Scholarship – Doctoral (grant ES D –
558643) and the FRQNT doctoral scholarship (grant no. 301750,
https://doi.org/10.69777/301750). TP was funded through award no. 223764/Z/21/Z
from the Wellcome Trust, by the Discovery Grant program of NSERC, through a
donation from the Courtois Foundation. MDC is funded by an IVADO Postdoctoral
Fellowship. This research was enabled in part by support provided by Calcul
Québec (calculquebec.ca) and the Digital Research Alliance of Canada
(alliancecan.ca). We thank the members of the *Laboratoire d’Écologie Prédictive
et Interprétable pour la Crise de la Biodiversité* in Montréal, QC, and of the
Predictive Ecology team at the *Pacific Forestry Centre* in Victoria, BC,
<!--aaaw <3--> for their constructive comments during discussions of this
manuscript.
